version: '3.8'
services:
  api:
    image: datascientest/fastapi:1.0.0 
    container_name: api_container
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - LOG=1
  test_authentication:
    image: tests_image
    container_name: test_authentication
    command: python3 test_authentication.py
    volumes:
      - ./log.txt:/app/api_log.txt
    environment:
      - LOG=1
    depends_on:
      - api
  test_authorization:
    image: tests_image
    container_name: test_authorization
    command: python3 test_authorization.py
    volumes:
      - ./log.txt:/app/api_log.txt
    environment:
      - LOG=1
    depends_on:
      - api
      - test_authentication
  test_content:
    image: tests_image
    container_name: test_content
    command: python3 test_content.py
    volumes:
      - ./log.txt:/app/api_log.txt
    environment:
      - LOG=1
    depends_on:
      - api
      - test_authorization
